import Link from 'next/link'
import './globals.css'
import type { Metadata } from 'next'
import Header from '@/components/Header'
import NoticeBanner from '@/components/NoticeBanner'


export const metadata: Metadata = {
  title: '알짜통',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (

    <html>

      <body>
        <div> 
          <Header />
        </div>
        {children}
        <div>
          <NoticeBanner />
        </div>

        <ul >
          <li><Link href="/create">등록</Link></li>
          <li><Link href="/search">조회</Link></li>
          <li><Link href="/manage">관리</Link></li>
        </ul>
      </body>
    </html>

  )
}
