export const BigDistrict = [
  { id: "서울", title: "서울" },
  { id: "인천", title: "인천" },
  { id: "경기도", title: "경기도" },
];

export const SmallDistrict = {
  인천: [
    { id: "강화군", title: "강화군" },
    { id: "계양구", title: "계양구" },
    { id: "남동구", title: "남동구" },
    { id: "동구", title: "동구" },
    { id: "미추홀구", title: "미추홀구" },
    { id: "부평구", title: "부평구" },
    { id: "서구", title: "서구" },
    { id: "연수구", title: "연수구" },
    { id: "옹진군", title: "옹진군" },
    { id: "중구", title: "중구" },
  ],
  서울: [
    { id: "강남구", title: "강남구" },
    { id: "강동구", title: "강동구" },
    { id: "강북구", title: "강북구" },
    { id: "강서구", title: "강서구" },
    { id: "관악구", title: "관악구" },
    { id: "광진구", title: "광진구" },
    { id: "구로구", title: "구로구" },
    { id: "금천구", title: "금천구" },
    { id: "노원구", title: "노원구" },
    { id: "도봉구", title: "도봉구" },
    { id: "동대문구", title: "동대문구" },
    { id: "동작구", title: "동작구" },
    { id: "마포구", title: "마포구" },
    { id: "서대문구", title: "서대문구" },
    { id: "서초구", title: "서초구" },
    { id: "성동구", title: "성동구" },
    { id: "성북구", title: "성북구" },
    { id: "송파구", title: "송파구" },
    { id: "양천구", title: "양천구" },
    { id: "영등포구", title: "영등포구" },
    { id: "용산구", title: "용산구" },
    { id: "은평구", title: "은평구" },
    { id: "종로구", title: "종로구" },
    { id: "중랑군", title: "중랑군" },
  ],
  경기도: [
    { id: "수원시", title: "수원시" },
    { id: "성남시", title: "성남시" },
    { id: "용인시", title: "용인시" },
    { id: "고양시", title: "고양시" },
    { id: "부천시", title: "부천시" },
    { id: "안산시", title: "안산시" },
    { id: "남양주시", title: "남양주시" },
    { id: "화성시", title: "화성시" },
    { id: "안양시", title: "안양시" },
    { id: "평택시", title: "평택시" },
    { id: "의정부시", title: "의정부시" },
    { id: "시흥시", title: "시흥시" },
    { id: "파주시", title: "파주시" },
    { id: "광명시", title: "광명시" },
    { id: "김포시", title: "김포시" },
    { id: "군포시", title: "군포시" },
    { id: "광주시", title: "광주시" },
    { id: "이천시", title: "이천시" },
    { id: "양주시", title: "양주시" },
    { id: "오산시", title: "오산시" },
    { id: "구리시", title: "구리시" },
    { id: "안성시", title: "안성시" },
    { id: "포천시", title: "포천시" },
    { id: "의왕시", title: "의왕시" },
    { id: "하남시", title: "하남시" },
    { id: "여주시", title: "여주시" },
    { id: "양평군", title: "양평군" },
    { id: "과천시", title: "과천시" },
    { id: "가평군", title: "가평군" },
    { id: "연천군", title: "연천군" },
    { id: "동두천시", title: "동두천시" },
  ],
};
