export const seniorWishList = [
    {
      wish_list_id: 1,
      senior_id: 1,
      location: "서울",
      location_detail: "강남구",
      job_code_number: 11,
      job_code_name: "농업",
      priority: 1,
      salary: 800,
      work_hour: 8,
      work_type: 1,
      etc: "없음",
    },
    {
      wish_list_id: 2,
      senior_id: 1,
      location: "서울",
      location_detail: "동대문구",
      job_code_number: 12,
      job_code_name: "임업",
      priority: 1,
      salary: 800,
      work_hour: 8,
      work_type: 1,
      etc: "없음",
    },
    {
      wish_list_id: 3,
      senior_id: 1,
      location: "경기도",
      location_detail: "수원시",
      job_code_number: 13,
      job_code_name: "제조업",
      priority: 1,
      salary: 800,
      work_hour: 8,
      work_type: 1,
      etc: "없음",
    },
    {
      wish_list_id: 4,
      senior_id: 2,
      location: "서울",
      location_detail: "강남구",
      job_code_number: 11,
      job_code_name: "농업",
      priority: 1,
      salary: 800,
      work_hour: 8,
      work_type: 1,
      etc: "없음",
    },
    {
      wish_list_id: 5,
      senior_id: 2,
      location: "서울",
      location_detail: "동대문구",
      job_code_number: 12,
      job_code_name: "임업",
      priority: 1,
      salary: 800,
      work_hour: 8,
      work_type: 1,
      etc: "없음",
    },
    {
      wish_list_id: 6,
      senior_id: 2,
      location: "경기도",
      location_detail: "수원시",
      job_code_number: 13,
      job_code_name: "제조업",
      priority: 1,
      salary: 800,
      work_hour: 8,
      work_type: 1,
      etc: "없음",
    },
  ];